name: Get output values between steps

on: workflow_dispatch

jobs:
  print_result:
    runs-on: ubuntu-latest

    steps:
      - name: "Example output creation"
        id: "my_step"
        run: |
          my_var="Hello World!!"
          echo "Output [$my_var]"
          echo "my_var=$my_var" >> $GITHUB_OUTPUT 

      - name: "Example output call between steps"
        run: |
              echo "Output [${{steps.my_step.outputs.my_var}}]"
