name: Notify on Job Success or Failure

on:
  workflow_run:
    workflows: ["Fetch and Store Secrets"]
    types:
      - completed

jobs:
  notify_on_failure:
    runs-on: ubuntu-latest

    steps:
      - name: Check Job Status
        run: echo "${{ github.event.workflow_run.conclusion }}"

      - name: Notify on Failure
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: |
          echo "Job failed. Notifying URL..."
          curl --location 'https://chat.googleapis.com/v1/spaces/AAAAEFWlcAM/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=dQVE1bh74oB27_okAsxgPBJkD-KF85xOvsm7uzSKQvQ' --header 'Content-Type: application/json' --header 'Cookie: COMPASS=dynamite-integration=CgAQ7e21qwYaUQAJa4lXjVCprTfVDPHdM_NuieAqWm2rDLlQwKspAL7MvG3s7hXeU-AO3QtfAejCykbYkv3nQrmZccrUvLfxllj4kFj2j5RsqJjuVuuSTFU9qTAB' --data '{ "text":"Fetch and Store Secrets is Failed" }'

      - name: Notify on Success
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          echo "Job Successful. Notifying URL..."
          curl --location 'https://chat.googleapis.com/v1/spaces/AAAAEFWlcAM/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=dQVE1bh74oB27_okAsxgPBJkD-KF85xOvsm7uzSKQvQ' --header 'Content-Type: application/json' --header 'Cookie: COMPASS=dynamite-integration=CgAQ7e21qwYaUQAJa4lXjVCprTfVDPHdM_NuieAqWm2rDLlQwKspAL7MvG3s7hXeU-AO3QtfAejCykbYkv3nQrmZccrUvLfxllj4kFj2j5RsqJjuVuuSTFU9qTAB' --data '{ "text":"Fetch and Store Secrets is Successful" }'
