name: Handle Success or Failure Event

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Hello Guys!!"

      - name: Handle Success
        if: ${{ success() }}
        run: |
          echo "Job succeeded!!"

      - name: Handle Failure
        if: ${{ failure() }}
        run: |
          echo "Job failed!!"
