name: Handle Success or Failure

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check Workflow Status
        run: echo "Workflow Status: ${{ github.event.workflow_run.conclusion }}"

      - name: Handle Success
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          echo "Workflow succeeded. Do something..."
          # Add your actions for success here

      - name: Handle Failure
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: |
          echo "Workflow failed. Do something else..."
          # Add your actions for failure here
