name: Build, Publish and Download Artifacts

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: list dist folder
        run: ls dist

      # - name: Print Workflow ID
      #   run: echo "${{ github.run_id }}"

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: dist

      - name: list dist folder
        run: ls dist

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install
        working-directory: ./dist

      - name: Deploy Application
        run: npm run start
        working-directory: ./dist
